name: quiz_master
description: "A quiz app for learning and fun."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # State management
  path_provider: ^2.1.5
  hydrated_bloc: ^10.1.1
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  get_it: ^8.2.0

  # UI and Theming
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.10.0

  # Localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Quiz API
  http: ^1.5.0

  # Splash
  flutter_native_splash: ^2.4.6

  # Tests
  mocktail: ^1.0.4
  fake_async: ^1.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo_2.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/