name: Deploy Flutter Web to GitHub Pages

on:
  workflow_run:
    workflows: ["Flutter CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # 4. Build web
      - name: Build web
        run: flutter build web --release --base-href /${{ github.event.repository.name }}/

      # 5. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
